#!/bin/bash
export PATH='/etc/storage/bin:/tmp/script:/etc/storage/script:/opt/usr/sbin:/opt/usr/bin:/opt/sbin:/opt/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin'
export LD_LIBRARY_PATH=/lib:/opt/lib
killall frpc frps
rm -f /dev/null ; mknod /dev/null c 1 3 ; chmod 666 /dev/null;
mkdir -p /tmp/frp
#启动frp功能后会运行以下脚本
#frp项目地址教程: https://github.com/fatedier/frp/blob/master/README_zh.md
#请自行修改 token 用于对客户端连接进行身份验证
# IP查询： http://119.29.29.29/d?dn=github.com

cat > "/tmp/frp/myfrpc.toml" <<-\EOF


[common]
server_addr = free.frp.vip
server_port = 3010
login_fail_exit = false
user = c2328b45-02cf-4fdf-a6da-87fed582e232
 
[ssh564]
type = tcp
local_ip = 192.168.123.123
local_port = 5211
remote_port = 10869













# ==========客户端配置1：==========

#[common]
#server_addr = free.frp.vip
#server_port = 3010
#login_fail_exit = false
#user = f2fdb995-789e-49d0-8c1e-b9c36c3437a0
 
#[ssh]
#type = tcp
#local_ip = 192.168.123.123
#local_port = 35455
#remote_port = 10147



# ==========客户端配置2：==========

#[common]
#server_addr = 38.47.53.73
#server_port = 7000
#token = moeyy.cn

#穿透需要 Web 访问的内网服务，例如群晖 NAS DSM 的管理界面。
#[moeyy5211_http]
#type = http
#local_ip = 192.168.123.1
#local_port = 5244
#custom_domains = alist.480583.xyz

#穿透需要 yacd 访问的内网服务，例如群晖 NAS DSM 的管理界面。
#[moeyy5201_http]
#type = http
#local_ip = 192.168.123.1
#local_port = 9090
#custom_domains = yacd.480583.xyz



# ==========客户端配置3：==========
#[common]
#网址：https://frp.wiki/

#server_addr = 47.243.51.51
#server_port = 7000
#tcp_mux = false
#protocol = tcp
#user = d69512b6e372022d
#token = ZDFreeFrp
#dns_server = 114.114.114.114
 
#[alist_480583hk2]
#privilege_mode = true
#type = http
#local_ip = 192.168.123.1
#local_port = 5244
#custom_domains = alist.480583.xyz
#use_encryption = true
#use_compression = true
 

# ==========客户端配置4：==========
#[common]
#网址：https://freefrp.net/
#server_addr = frp2.freefrp.net
#server_port = 7000
#token = freefrp.net

#[nass_480583_xyz_http] 
#type = http
#local_ip = 192.168.123.1
#local_port = 9090 
#custom_domains = nass.480583.xyz



# ==========客户端配置5：==========
#[common]
#网址：https://my.ksust.com/
#server_addr = ct.frp.vip
#server_port = 2090
#login_fail_exit = false
#user= 1a82dc2b-51bc-4bed-ac7d-8a720d1656be

#log_file = /dev/null
#log_level = info
#log_max_days = 3

#[nass_480583_xyz_http] 
#type = tcp
#local_ip = 192.168.123.1
#local_port = 5244 
#remote_port = 30580
#custom_domains = nass.480583.xyz











# ==========客户端配置：==========
#serverAddr = "frps.com" # 远端frp服务器ip或域名
#serverPort = 7000
#auth.token = "12345"
#loginFailExit = false
#log.to = "/dev/null"
#log.level = "info"
#log.maxDays = 3

#[[proxies]]
#name = "web"
#type = "http"
#localIP = "192.168.123.1"
#localPort = 80
#subdomain = "test"
#hostHeaderRewrite = "test.frps.com" #实际你内网访问的域名，可以供公网的域名不一致，如果一致可以不写
# ====================
EOF

#请手动配置【外部网络 (WAN) - 端口转发 (UPnP)】开启 WAN 外网端口
cat > "/tmp/frp/myfrps.toml" <<-\EOF
# ==========服务端配置：==========
bindAddr = "0.0.0.0"
bindPort = 7000
auth.token = "12345"
# webServer.addr = "127.0.0.1"
# webServer.port = 7500
# Dashboard 控制面板用户名密码，默认都为 admin
# webServer.user = "admin"
# webServer.password = "admin"
vhostHTTPPort = 88
subDomainHost = "frps.com"
transport.maxPoolCount = 50
#log.to = "/dev/null"
#log.level = "info"
#log.maxDays = 3
# ====================
EOF

#启动：
frpc_enable=`nvram get frpc_enable`
frpc_enable=${frpc_enable:-"0"}
frps_enable=`nvram get frps_enable`
frps_enable=${frps_enable:-"0"}
if [ "$frps_enable" = "1" ] ; then
    frps -c /tmp/frp/myfrps.toml 2>&1 &
fi
if [ "$frpc_enable" = "1" ] ; then
    [ "$frps_enable" = "1" ] && sleep 60
    frpc -c /tmp/frp/myfrpc.toml 2>&1 &
fi

